apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales-api
spec:
  selector:
    matchLabels:
      app: sales-api
  template:
    metadata:
      labels:
        app: sales-api
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      terminationGracePeriodSeconds: 60
      containers:
      - name: app
        image: sales-api-amd64:1.0
        ports:
        - name: app
          containerPort: 3000
        - name: app-debug
          containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: sales-api
spec:
  selector:
    app: sales-api
  ports:
  - name: app
    port: 3000
    targetPort: app
  - name: app-debug
    port: 4000
    targetPort: app-debug
